## A.I. Assignment 5

## Learning Goals

By the end of this lab, you should be able to:
* Get more familiar with tensors in pytorch 
* Create a simple multilayer perceptron model with pytorch
* Visualise the parameters


### Task

Build a fully connected feed forward network that adds two bits. Determine the a propper achitecture for this network (what database you use for this problem? how many layers? how many neurons on each layer? what is the activation function? what is the loss function? etc)

Create at least 3 such networks and compare their performance (how accurate they are?, how farst they are trained to get at 1 accuracy?)

Display for the best one the weights for each layer.


In [1]:
import torch
import torch.nn as nn
from collections import OrderedDict


In [2]:
# your code here
model1 = nn.Sequential(OrderedDict([
    ('hidden_net', nn.Linear(2,32)),
    ('hidden_act', nn.Sigmoid()),
    ('output_net', nn.Linear(32,2)),
    ('output_act', nn.Sigmoid())
]))
model2 = nn.Sequential(OrderedDict([
    ('hidden_net', nn.Linear(2,8)),
    ('hidden_act', nn.ReLU()),
    ('output_net', nn.Linear(8,2)),
    ('output_act', nn.Sigmoid())
]))
model3 = nn.Sequential(OrderedDict([
    ('hidden_net', nn.Linear(2,16)),
    ('hidden_act', nn.Sigmoid()),
    ('output_net', nn.Linear(16,2)),
    ('output_act', nn.Sigmoid())
]))

In [3]:
print(model1)
print(model2)
print(model3)

Sequential(
  (hidden_net): Linear(in_features=2, out_features=32, bias=True)
  (hidden_act): Sigmoid()
  (output_net): Linear(in_features=32, out_features=2, bias=True)
  (output_act): Sigmoid()
)
Sequential(
  (hidden_net): Linear(in_features=2, out_features=8, bias=True)
  (hidden_act): ReLU()
  (output_net): Linear(in_features=8, out_features=2, bias=True)
  (output_act): Sigmoid()
)
Sequential(
  (hidden_net): Linear(in_features=2, out_features=16, bias=True)
  (hidden_act): Sigmoid()
  (output_net): Linear(in_features=16, out_features=2, bias=True)
  (output_act): Sigmoid()
)


In [4]:
# your code here
data_in = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float)
print(data_in)

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])


In [5]:
# your code here
data_target = torch.tensor([[0, 0], [0, 1], [0, 1], [1, 0]], dtype=torch.float)
print(data_target)

tensor([[0., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])


In [6]:
# your code here
criterion1 = nn.MSELoss()
optimizer1 = torch.optim.Adam(model1.parameters(), lr=0.01)
criterion2 = nn.CrossEntropyLoss()
optimizer2 = torch.optim.SGD(model2.parameters(), lr=0.01, momentum=0.9)
criterion3 = nn.L1Loss()
optimizer3 = torch.optim.SGD(model3.parameters(), lr=0.01, momentum=0.9)

In [7]:
# your code here
# Train the model
def train(model, inputs, outputs, criterion, optimizer):
    for epoch in range(100):
        optimizer.zero_grad()
        loss = criterion(model(inputs), outputs)
        loss.backward()
        optimizer.step()

In [8]:
# your code here
for model in [model1, model2, model3]:
    if model == model1:
        criterion = criterion1
        optimizer = optimizer1
    if model == model2:
        criterion = criterion2
        optimizer = optimizer2
    if model == model3:
        criterion = criterion3
        optimizer = optimizer3
    train(model, data_in, data_target, criterion, optimizer)
    outputs = model(data_in)
    predicted = (outputs >=0.5).float()
    print(predicted)
    accuracy = (predicted == data_target).float().mean()
    print(f'Training Accuracy: {accuracy.item()*100}')

tensor([[0., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])
Training Accuracy: 100.0
tensor([[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]])
Training Accuracy: 62.5
tensor([[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]])
Training Accuracy: 62.5


In [9]:
# your code here
print('Weight of network1 :\n',model1[0].weight)
print('Weight of network2 :\n',model2[0].weight)
print('Weight of network3 :\n',model3[0].weight)


Weight of network1 :
 Parameter containing:
tensor([[-1.3750,  0.2599],
        [-1.6167, -0.4605],
        [ 1.1121,  0.7643],
        [ 1.7055,  0.6342],
        [ 0.3950,  0.7232],
        [-1.5138, -0.3796],
        [ 1.8460,  1.8926],
        [-1.3522, -1.5757],
        [-0.1028,  0.0304],
        [ 1.1310,  1.3414],
        [ 0.2228,  1.4202],
        [ 0.7743,  1.3382],
        [-0.1841, -1.2329],
        [ 1.2972,  0.8071],
        [-0.6247, -1.3120],
        [ 0.6538,  0.4297],
        [ 0.0842, -1.5751],
        [ 0.1314,  0.1331],
        [-1.5196, -1.0753],
        [-0.8609, -1.2551],
        [-1.2550, -1.2251],
        [ 0.1148,  0.2359],
        [-0.2617, -0.0129],
        [ 0.9688,  1.4007],
        [-0.1862, -1.5389],
        [-1.0369, -1.4186],
        [ 0.5447, -1.3365],
        [-1.0851, -1.3625],
        [-0.9758, -0.8136],
        [ 1.7306,  1.9294],
        [-1.2929, -0.8402],
        [-1.3337, -1.2364]], requires_grad=True)
Weight of network2 :
 Parameter contain